# Generated by Django 4.2.9 on 2026-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='max_patients_per_slot',
            field=models.IntegerField(default=1, help_text='Maximum number of patients per time slot'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Account approval status (for patients)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_STARTED', help_text='KYC verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_id',
            field=models.FileField(blank=True, help_text='Temporary ID uploaded during registration', null=True, upload_to='temporary_ids/%Y/%m/%d/'),
        ),
    ]
