# Generated by Django 4.2.9 on 2026-01-28 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_doctorschedule_max_patients_per_slot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_image', models.ImageField(help_text='Uploaded ID card image', upload_to='id_cards/%Y/%m/%d/')),
                ('id_card_type', models.CharField(choices=[('DRIVERS_LICENSE', "Driver's License"), ('PASSPORT', 'Passport'), ('NATIONAL_ID', 'National ID'), ('PHILHEALTH_ID', 'PhilHealth ID'), ('OTHER', 'Other Government ID')], help_text='Type of ID card uploaded', max_length=50)),
                ('id_number', models.CharField(blank=True, help_text='Extracted ID number from OCR', max_length=100)),
                ('id_full_name', models.CharField(blank=True, help_text='Full name extracted from ID card', max_length=255)),
                ('id_date_of_birth', models.DateField(blank=True, help_text='Date of birth extracted from ID', null=True)),
                ('id_address', models.TextField(blank=True, help_text='Address extracted from ID card')),
                ('id_face_image', models.ImageField(blank=True, help_text='Extracted face image from ID card', null=True, upload_to='id_faces/%Y/%m/%d/')),
                ('id_face_encoding', models.JSONField(blank=True, help_text='Face encoding from ID card (128-dimensional array)', null=True)),
                ('live_face_image', models.ImageField(help_text='Live face photo captured during registration', upload_to='live_faces/%Y/%m/%d/')),
                ('live_face_encoding', models.JSONField(help_text='Face encoding from live photo (128-dimensional array)')),
                ('face_match_score', models.FloatField(help_text='Face matching distance (0-1, lower is better match)')),
                ('face_match_threshold', models.FloatField(default=0.6, help_text='Threshold used for face matching')),
                ('is_face_verified', models.BooleanField(default=False, help_text='Whether face match verification passed')),
                ('face_recognition_enabled', models.BooleanField(default=False, help_text='Enable face recognition login for this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from manual verification process')),
                ('user', models.OneToOneField(help_text='User associated with this biometric data', on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff member who manually verified the biometric data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_biometrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometric Data',
                'verbose_name_plural': 'Biometric Data',
                'db_table': 'biometric_data',
                'indexes': [models.Index(fields=['user'], name='biometric_d_user_id_d72ddc_idx'), models.Index(fields=['is_face_verified'], name='biometric_d_is_face_cd98c5_idx'), models.Index(fields=['face_recognition_enabled'], name='biometric_d_face_re_4e4411_idx')],
            },
        ),
    ]
