# Generated by Django 4.2.9 on 2026-01-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_biometricdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricdata',
            name='biometric_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of biometric data (ID + face)', max_length=64),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='biometric_id',
            field=models.CharField(blank=True, default='', help_text='Unique identifier for blockchain registration', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='block_number',
            field=models.IntegerField(blank=True, help_text='Block number where transaction was mined', null=True),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='blockchain_address',
            field=models.CharField(blank=True, help_text='Ethereum address that registered this data', max_length=42),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='is_blockchain_verified',
            field=models.BooleanField(default=False, help_text='Whether data is verified on blockchain'),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Blockchain Confirmation'), ('CONFIRMED', 'Confirmed on Blockchain'), ('FAILED', 'Failed to Register on Blockchain')], default='PENDING', help_text='Blockchain registration status', max_length=20),
        ),
        migrations.AddField(
            model_name='biometricdata',
            name='transaction_hash',
            field=models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='id_card_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'PhilID / National ID (ePhilID)'), ('DRIVERS_LICENSE', "Driver's License"), ('PHILHEALTH_ID', 'PhilHealth ID')], help_text='Type of ID card uploaded', max_length=50),
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['biometric_id'], name='biometric_d_biometr_31843b_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricdata',
            index=models.Index(fields=['status'], name='biometric_d_status_729595_idx'),
        ),
    ]
