# Generated by Django 4.2.9 on 2026-01-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_id_card_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, help_text='ID number from scanned Philippine ID', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(blank=True, choices=[('NATIONAL_ID', 'PhilID / National ID (ePhilID)'), ('DRIVERS_LICENSE', "Driver's License"), ('PHILHEALTH_ID', 'PhilHealth ID')], help_text='Type of Philippine ID used for registration', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
