# Generated by Django 4.2.9 on 2026-01-28 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_make_biometric_fields_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biometricdata',
            options={'ordering': ['-created_at'], 'verbose_name': 'Biometric Data', 'verbose_name_plural': 'Biometric Data'},
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='users_biome_user_id_271a7e_idx',
            old_name='biometric_d_user_id_d72ddc_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='users_biome_biometr_864f87_idx',
            old_name='biometric_d_biometr_31843b_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='users_biome_status_25cfe4_idx',
            old_name='biometric_d_status_729595_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='users_biome_is_face_2b9758_idx',
            old_name='biometric_d_is_face_cd98c5_idx',
        ),
        migrations.RenameIndex(
            model_name='biometricdata',
            new_name='users_biome_face_re_dc938b_idx',
            old_name='biometric_d_face_re_4e4411_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='biometric_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of biometric data', max_length=64),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='biometric_id',
            field=models.CharField(blank=True, default='', help_text='Unique identifier for blockchain (BIO_YYYYMMDD_UUID)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='block_number',
            field=models.IntegerField(blank=True, help_text='Block number where data was registered', null=True),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='blockchain_address',
            field=models.CharField(blank=True, help_text='Ethereum address for blockchain registration', max_length=42),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='face_match_score',
            field=models.FloatField(help_text='Face matching distance (0-1, lower = better match)'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='face_match_threshold',
            field=models.FloatField(default=0.6, help_text='Threshold used for verification'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False, help_text='Whether user can use face login'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='id_card_type',
            field=models.CharField(choices=[('NATIONAL_ID', 'PhilID / National ID (ePhilID)'), ('DRIVERS_LICENSE', "Driver's License"), ('PHILHEALTH_ID', 'PhilHealth ID')], help_text='Type of Philippine ID', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='is_face_verified',
            field=models.BooleanField(default=False, help_text='Whether face verification passed'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='live_face_encoding',
            field=models.JSONField(help_text='Face encoding from live selfie (128-dim array)'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='live_face_image',
            field=models.ImageField(help_text='Live selfie for verification', upload_to='live_faces/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('CONFIRMED', 'Confirmed on Blockchain'), ('FAILED', 'Blockchain Registration Failed')], default='PENDING', help_text='Blockchain registration status', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Notes from manual verification'),
        ),
        migrations.AlterField(
            model_name='biometricdata',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who verified this data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_biometrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='biometricdata',
            table=None,
        ),
    ]
