# Generated by Django 4.2.9 on 2026-01-14 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=255, unique=True)),
                ('document_type', models.CharField(choices=[('KYC_ID', 'KYC Identity Document'), ('KYC_ADDRESS', 'KYC Address Proof'), ('KYC_PHOTO', 'KYC Photo'), ('OTHER', 'Other Document')], max_length=20)),
                ('document_name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='mock_pdfs/')),
                ('document_hash', models.CharField(max_length=64)),
                ('blockchain_address', models.CharField(blank=True, max_length=42)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Blockchain Confirmation'), ('CONFIRMED', 'Confirmed on Blockchain'), ('FAILED', 'Failed to Register')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Document',
                'verbose_name_plural': 'Blockchain Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REGISTER', 'Document Registration'), ('VERIFY', 'Document Verification')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=66)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='blockchain.blockchaindocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Transaction',
                'verbose_name_plural': 'Blockchain Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
