# Generated by Django 4.2.9 on 2026-01-14 17:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('LAB_RESULT', 'Laboratory Result'), ('XRAY', 'X-Ray Report'), ('CT_SCAN', 'CT Scan'), ('MRI', 'MRI Scan'), ('PRESCRIPTION', 'Prescription'), ('CONSULTATION', 'Consultation Notes'), ('DIAGNOSIS', 'Diagnosis Report'), ('VACCINATION', 'Vaccination Record'), ('OTHER', 'Other Medical Document')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('date_of_service', models.DateField(help_text='Date when the medical service was provided')),
                ('document_file', models.FileField(upload_to='medical_records/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx'])])),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('document_id', models.CharField(max_length=255, unique=True)),
                ('document_hash', models.CharField(max_length=64)),
                ('blockchain_address', models.CharField(blank=True, max_length=42)),
                ('transaction_hash', models.CharField(blank=True, max_length=66)),
                ('block_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Blockchain Confirmation'), ('CONFIRMED', 'Confirmed on Blockchain'), ('FAILED', 'Failed to Register')], default='PENDING', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_on_blockchain_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'role': 'IT_STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-date_of_service', '-created_at'],
                'indexes': [models.Index(fields=['patient', 'date_of_service'], name='blockchain__patient_e38817_idx'), models.Index(fields=['document_id'], name='blockchain__documen_d808ea_idx'), models.Index(fields=['status'], name='blockchain__status_f88261_idx')],
            },
        ),
    ]
