# Generated by Django 4.2.9 on 2026-01-27 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blockchain', '0004_alter_medicalrecord_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', help_text='Approval status for external records', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['NURSE', 'DOCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_external',
            field=models.BooleanField(default=False, help_text='Whether this record was created externally'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
