# Generated by Django 4.2.9 on 2026-01-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_medicalrecord_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
    ]
