# Generated by Django 4.2.9 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('IT_STAFF', 'Medical Data Administrator'), ('PATIENT', 'Patient')], default='PATIENT', max_length=10),
        ),
    ]
