# Generated by Django 4.2.9 on 2026-01-28 18:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (must be unique)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional category description', null=True)),
                ('slug', models.SlugField(help_text='URL-friendly category identifier', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when category was last updated')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(help_text='Detailed product description')),
                ('short_description', models.CharField(blank=True, help_text='Brief product summary', max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price (must be positive)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for profit calculation', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Available stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert threshold for low stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(help_text='Stock Keeping Unit (unique identifier)', max_length=100, unique=True)),
                ('barcode', models.CharField(blank=True, help_text='Product barcode', max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Product weight in kg', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('discontinued', 'Discontinued'), ('out_of_stock', 'Out of Stock')], default='draft', help_text='Current product status', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether product is featured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether product is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when product was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when product was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Product category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(help_text='Review title', max_length=200)),
                ('comment', models.TextField(help_text='Review comment')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='Whether this is a verified purchase')),
                ('is_approved', models.BooleanField(default=False, help_text='Whether review is approved for display')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when review was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when review was last updated')),
                ('product', models.ForeignKey(help_text='Product being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='products_ca_slug_da4386_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='products_ca_is_acti_a2d000_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', '-created_at'], name='products_pr_product_c9febd_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['is_approved'], name='products_pr_is_appr_790eda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_pr_status_041708_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='products_pr_created_bce1a7_idx'),
        ),
    ]
